openapi: 3.0.1
info:
  title: Onboarding available to integrators
  contact:
    email: developer@mobilepay.dk
  version: v1
paths:
  /api/v1/credentials:
    get:
      tags:
        - PSP Onboarding
      summary: Get Credentials
      description: 'Get IntegratorName, ClientName and Active Status for the specified x-ibm-client-Id'
      parameters:
        - name: CorrelationId
          in: header
          description: CorrelationId used for logging
          schema:
            type: string
      responses:
        '200':
          description: Success
        '409':
          description: Domain error response
    post:
      tags:
        - PSP Onboarding
      summary: Create Credentials
      description: 'Generates, saves and returns a x-ibm-client-id and x-ibm-client-secret, used for calling product endpoints'
      parameters:
        - name: CorrelationId
          in: header
          description: CorrelationId used for logging
          schema:
            type: string
      responses:
        '200':
          description: Success
        '409':
          description: Domain error response
    servers:
      - url: https://api.mobilepay.dk/cardpassthrough-kongonboarding-restapi
        description: Production server (uses **live** data)
      - url: https://api.sandbox.mobilepay.dk/cardpassthrough-kongonboarding-restapi
        description: Production server (uses **test** data)
  /api/v1/credentials/secret:
    patch:
      tags:
        - PSP Onboarding
      summary: Update secret
      description: 'Generates, replaces and returns a new x-ibm-client-secret'
      parameters:
        - name: CorrelationId
          in: header
          description: CorrelationId used for logging
          schema:
            type: string
      responses:
        '200':
          description: Success
        '409':
          description: Domain error response
    servers:
      - url: https://api.mobilepay.dk/cardpassthrough-kongonboarding-restapi
        description: Production server (uses **live** data)
      - url: https://api.sandbox.mobilepay.dk/cardpassthrough-kongonboarding-restapi
        description: Production server (uses **test** data)
components: { }